FutsalReservation/Controllers/CourtController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FutsalReservation.Data;
using FutsalReservation.Data.Entities;

namespace FutsalReservation.Controllers
{
    public class CourtController : Controller
    {
        private readonly FutsalReservationContext _context;
        private List<int> _hourTimings = new List<int> { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 };

        public CourtController(FutsalReservationContext context)
        {
            _context = context;
        }

        // GET: Court
        public async Task<IActionResult> Index()
        {
            var courtReservations = _context.Court.Include(r => r.Reservations).Include(t => t.Timings);
            //return View(await _context.Court.ToListAsync());
            return View(await courtReservations.ToListAsync());
        }

        // GET: Court/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Court == null)
            {
                return NotFound();
            }

            var court = await _context.Court
                .FirstOrDefaultAsync(m => m.Id == id);
            if (court == null)
            {
                return NotFound();
            }

            return View(court);
        }

        // GET: Court/Create
        public IActionResult Create()
        {
           
            return View();
        }

        // POST: Court/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Court court)
        {
            if (ModelState.IsValid)
            {
                _context.Add(court);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(court);
        }

        // GET: Court/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Court == null)
            {
                return NotFound();
            }

            var court = await _context.Court.FindAsync(id);
            if (court == null)
            {
                return NotFound();
            }
            ViewData["HourTimings"] = new SelectList(_hourTimings);
            return View(court);
        }

        // POST: Court/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Court court,string endTime,string startTime)
        {
           Timing timing = new Timing(startTime, endTime);
            if (id != court.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var toUpdateCourt = await _context.Court.FindAsync(id);
                    if (toUpdateCourt != null)
                    {
                        toUpdateCourt.Timings = new List<Timing>();
                        toUpdateCourt.Timings.Add(timing);
                        toUpdateCourt.Name = court.Name;
                        await _context.SaveChangesAsync();
                    }
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourtExists(court.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(court);
        }

        // GET: Court/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Court == null)
            {
                return NotFound();
            }

            var court = await _context.Court
                .FirstOrDefaultAsync(m => m.Id == id);
            if (court == null)
            {
                return NotFound();
            }

            return View(court);
        }

        // POST: Court/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Court == null)
            {
                return Problem("Entity set 'FutsalReservationContext.Court'  is null.");
            }
            var court = await _context.Court.FindAsync(id);
            if (court != null)
            {
                _context.Court.Remove(court);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourtExists(int id)
        {
          return _context.Court.Any(e => e.Id == id);
        }

        public async Task<IActionResult> ShowReservations(int? id)
        {
            if (id == null || _context.Court == null)
            {
                return NotFound();
            }
            var court = _context.Court.First(c => c.Id == id);
            var courtReservations = await _context.Reservation.Include(r => r.User).Where(r => r.CourtId == id).ToListAsync();
            if (courtReservations.Count == 0)
            {
                ViewData["Message"] = "No reservations for " + court.Name;
            }
            ViewData["UserId"] = id;
            return View(courtReservations);
        }
    }
}

FutsalReservation/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FutsalReservation.Data;
using FutsalReservation.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace FutsalReservation.Controllers
{
    public class ReservationController : Controller
    {
        private readonly FutsalReservationContext _context;
        private List<String> _timings = new List<String> { "5am - 6am", "6am - 7am", "7am - 8am", "8am - 9am", "9am - 10am", "10am - 11am", "11am - 12pm", "12pm - 1pm", "1pm - 2pm", "2pm - 3pm", "3pm - 4pm", "4pm - 5pm", "5pm - 6pm", "6pm - 7pm", "7pm - 8pm", "8pm - 9pm", "9pm - 10pm" };
        private readonly DateTime _date = DateTime.Now;
        public List<String> availableTimings = new List<String>();
        public ReservationController(FutsalReservationContext context)
        {
            _context = context;
        }

        // GET: Reservation
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var currentUserName = User.Claims.First(c => c.Type == "UserName").Value;
            var currentUser = _context.User.First(u => u.Username == currentUserName);
            ViewData["UserId"] = currentUser.Id;
            var futsalReservationContext = _context.Reservation.Include(r => r.Court).Include(r => r.User);
            return View(await futsalReservationContext.ToListAsync());
        }

        // GET: Reservation/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Reservation == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation
                .Include(r => r.Court)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.ReservationId == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // GET: Reservation/Create
        [Authorize(Roles = "Admin, Normal")]
        public IActionResult UserCreate(int? id)
        {
            var user = _context.User.Where(u => u.Id == id);
            var today = $"{_date.Year}/{_date.Month}/{_date.Day}";
            AvailableTimings(today);
            ViewData["Today"] = $"{_date.Year}/{_date.Month}/{_date.Day}";
            ViewData["Timings"] = new SelectList(availableTimings);
            ViewData["CourtId"] = new SelectList(_context.Court, "Id", "Name");
            ViewData["UserId"] = new SelectList(user, "Id", "Email");
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            var today = $"{_date.Year}/{_date.Month}/{_date.Day}";
            AvailableTimings(today);
            ViewData["Today"] = $"{_date.Year}/{_date.Month}/{_date.Day}";
            ViewData["Timings"] = new SelectList(_timings);
            ViewData["CourtId"] = new SelectList(_context.Court, "Id", "Name");
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Email");
            return View();
        }

        // POST: Reservation/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("ReservationId,UserId,CourtId,ReservationDate,ReservationTime")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourtId"] = new SelectList(_context.Court, "Id", "Name", reservation.CourtId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Email", reservation.UserId);
            return View(reservation);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Normal")]
        public async Task<IActionResult> UserCreate([Bind("ReservationId,UserId,CourtId,ReservationDate,ReservationTime")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                var userName = User.Claims.First(c => c.Type == "UserName").Value;
                var user = _context.User.First(u => u.Username == userName);
                return RedirectToAction("ShowReservations", "User", user);
            }
            ViewData["CourtId"] = new SelectList(_context.Court, "Id", "Name", reservation.CourtId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Email", reservation.UserId);
            return View(reservation);
        }
        // GET: Reservation/Edit/5
        [Authorize(Roles = "Admin, Normal")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Reservation == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation.FindAsync(id);
            if (reservation == null)
            {
                return NotFound();
            }
            var today = $"{_date.Year}/{_date.Month}/{_date.Day}";
            AvailableTimings(today);
            ViewData["Today"] = $"{_date.Year}/{_date.Month}/{_date.Day}";
            ViewData["Timings"] = new SelectList(availableTimings);
            ViewData["CourtId"] = new SelectList(_context.Court, "Id", "Name", reservation.CourtId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Email", reservation.UserId);
            return View(reservation);
        }

        // POST: Reservation/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Normal")]
        public async Task<IActionResult> Edit(int id, [Bind("ReservationId,UserId,CourtId,ReservationDate,ReservationTime")] Reservation reservation)
        {
            if (id != reservation.ReservationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reservation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationExists(reservation.ReservationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourtId"] = new SelectList(_context.Court, "Id", "Name", reservation.CourtId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "Email", reservation.UserId);
            return View(reservation);
        }

        // GET: Reservation/Delete/5
        [Authorize(Roles = "Admin, Normal")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Reservation == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation
                .Include(r => r.Court)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.ReservationId == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // POST: Reservation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Normal")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Reservation == null)
            {
                return Problem("Entity set 'FutsalReservationContext.Reservation'  is null.");
            }
            var reservation = await _context.Reservation.FindAsync(id);
            if (reservation != null)
            {
                _context.Reservation.Remove(reservation);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
          return _context.Reservation.Any(e => e.ReservationId == id);
        }

        public void AvailableTimings(string? date)
        {
            var reservationsForToday = _context.Reservation.Where(r => r.ReservationDate == date).ToList();
            if (reservationsForToday.Count == 0)
            {
                availableTimings = _timings.ToList();
            }
            else
            {
                List<String> reservedTimings = new List<String>();
                foreach (var reservation in reservationsForToday)
                {
                    reservedTimings.Add(reservation.ReservationTime);
                }
                availableTimings = _timings.Except(reservedTimings).ToList();
            }
        }
    }
}

FutsalReservation/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FutsalReservation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FutsalReservation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="navbar-brand">FutsalReservation</a>    
                }
                else{
                    <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Login">FutsalReservation</a>
                }
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">Sign Up</a>
                            </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Court" asp-action="Index">Court</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Index">Reservation</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Details" asp-route-id="@ViewBag.UserId">@User.Claims.First(c => c.Type == "UserName").Value</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Log Out</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FutsalReservation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>